/* Built-in exercise library. `id` values are stable — history references them,
   so never rename, reuse or repurpose one. Adding is always safe.

   `muscle` is display grouping only (it drives the picker's sections and their
   order via MUSCLE_ORDER); nothing is persisted against it, so regrouping an
   exercise later is harmless. The groups are deliberately finer than
   chest/back/legs — at this library size a single "Legs" section would be
   forty rows deep in the picker. */
const EXERCISE_LIBRARY = [
  // ---------- Chest ----------
  { id: 'bench-press',        name: 'Barbell Bench Press',   muscle: 'Chest' },
  { id: 'incline-bench',      name: 'Incline Bench Press',   muscle: 'Chest' },
  { id: 'chest-press',        name: 'Chest Press (Machine)', muscle: 'Chest' },
  { id: 'db-bench',           name: 'Dumbbell Bench Press',  muscle: 'Chest' },
  { id: 'cable-fly',          name: 'Cable Fly',             muscle: 'Chest' },
  { id: 'push-up',            name: 'Push-Up',               muscle: 'Chest' },
  { id: 'dip',                name: 'Chest Dip',             muscle: 'Chest' },
  { id: 'decline-bench',      name: 'Decline Bench Press',   muscle: 'Chest' },
  { id: 'close-grip-bench',   name: 'Close-Grip Bench Press', muscle: 'Chest' },
  { id: 'db-incline-press',   name: 'Incline Dumbbell Press', muscle: 'Chest' },
  { id: 'db-decline-press',   name: 'Decline Dumbbell Press', muscle: 'Chest' },
  { id: 'db-fly',             name: 'Dumbbell Fly',          muscle: 'Chest' },
  { id: 'incline-db-fly',     name: 'Incline Dumbbell Fly',  muscle: 'Chest' },
  { id: 'low-cable-fly',      name: 'Low-to-High Cable Fly', muscle: 'Chest' },
  { id: 'high-cable-fly',     name: 'High-to-Low Cable Fly', muscle: 'Chest' },
  { id: 'pec-deck',           name: 'Pec Deck',              muscle: 'Chest' },
  { id: 'incline-machine-press', name: 'Incline Press (Machine)', muscle: 'Chest' },
  { id: 'smith-bench',        name: 'Smith Machine Bench Press', muscle: 'Chest' },
  { id: 'deficit-push-up',    name: 'Deficit Push-Up',       muscle: 'Chest' },
  { id: 'incline-push-up',    name: 'Incline Push-Up',       muscle: 'Chest' },
  { id: 'svend-press',        name: 'Svend Press',           muscle: 'Chest' },
  { id: 'dumbbell-pullover',  name: 'Dumbbell Pullover',     muscle: 'Chest' },

  // ---------- Back ----------
  { id: 'deadlift',           name: 'Deadlift',              muscle: 'Back' },
  { id: 'barbell-row',        name: 'Barbell Row',           muscle: 'Back' },
  { id: 'db-row',             name: 'Dumbbell Row',          muscle: 'Back' },
  { id: 'lat-pulldown',       name: 'Lat Pulldown',          muscle: 'Back' },
  { id: 'pull-up',            name: 'Pull-Up',               muscle: 'Back' },
  { id: 'seated-row',         name: 'Seated Cable Row',      muscle: 'Back' },
  { id: 'face-pull',          name: 'Face Pull',             muscle: 'Back' },
  { id: 'chin-up',            name: 'Chin-Up',               muscle: 'Back' },
  { id: 'neutral-pull-up',    name: 'Neutral-Grip Pull-Up',  muscle: 'Back' },
  { id: 'assisted-pull-up',   name: 'Assisted Pull-Up',      muscle: 'Back' },
  { id: 'pendlay-row',        name: 'Pendlay Row',           muscle: 'Back' },
  { id: 't-bar-row',          name: 'T-Bar Row',             muscle: 'Back' },
  { id: 'chest-supported-row', name: 'Chest-Supported Row',  muscle: 'Back' },
  { id: 'machine-row',        name: 'Machine Row',           muscle: 'Back' },
  { id: 'inverted-row',       name: 'Inverted Row',          muscle: 'Back' },
  { id: 'meadows-row',        name: 'Meadows Row',           muscle: 'Back' },
  { id: 'wide-lat-pulldown',  name: 'Wide-Grip Lat Pulldown', muscle: 'Back' },
  { id: 'close-lat-pulldown', name: 'Close-Grip Lat Pulldown', muscle: 'Back' },
  { id: 'straight-arm-pulldown', name: 'Straight-Arm Pulldown', muscle: 'Back' },
  { id: 'rack-pull',          name: 'Rack Pull',             muscle: 'Back' },
  { id: 'sumo-deadlift',      name: 'Sumo Deadlift',         muscle: 'Back' },
  { id: 'trap-bar-deadlift',  name: 'Trap Bar Deadlift',     muscle: 'Back' },
  { id: 'deficit-deadlift',   name: 'Deficit Deadlift',      muscle: 'Back' },
  { id: 'back-extension',     name: 'Back Extension',        muscle: 'Back' },
  { id: 'good-morning',       name: 'Good Morning',          muscle: 'Back' },
  { id: 'shrug',              name: 'Shrug',                 muscle: 'Back' },
  { id: 'db-shrug',           name: 'Dumbbell Shrug',        muscle: 'Back' },

  // ---------- Shoulders ----------
  { id: 'overhead-press',     name: 'Overhead Press',        muscle: 'Shoulders' },
  { id: 'db-shoulder-press',  name: 'Dumbbell Shoulder Press', muscle: 'Shoulders' },
  { id: 'lateral-raise',      name: 'Lateral Raise',         muscle: 'Shoulders' },
  { id: 'rear-delt-fly',      name: 'Rear Delt Fly',         muscle: 'Shoulders' },
  { id: 'upright-row',        name: 'Upright Row',           muscle: 'Shoulders' },
  { id: 'seated-db-press',    name: 'Seated Dumbbell Press', muscle: 'Shoulders' },
  { id: 'arnold-press',       name: 'Arnold Press',          muscle: 'Shoulders' },
  { id: 'machine-shoulder-press', name: 'Shoulder Press (Machine)', muscle: 'Shoulders' },
  { id: 'push-press',         name: 'Push Press',            muscle: 'Shoulders' },
  { id: 'behind-neck-press',  name: 'Behind-the-Neck Press', muscle: 'Shoulders' },
  { id: 'cable-lateral-raise', name: 'Cable Lateral Raise',  muscle: 'Shoulders' },
  { id: 'machine-lateral-raise', name: 'Lateral Raise (Machine)', muscle: 'Shoulders' },
  { id: 'front-raise',        name: 'Front Raise',           muscle: 'Shoulders' },
  { id: 'plate-front-raise',  name: 'Plate Front Raise',     muscle: 'Shoulders' },
  { id: 'reverse-pec-deck',   name: 'Reverse Pec Deck',      muscle: 'Shoulders' },
  { id: 'bent-over-lateral',  name: 'Bent-Over Lateral Raise', muscle: 'Shoulders' },
  { id: 'landmine-press',     name: 'Landmine Press',        muscle: 'Shoulders' },
  { id: 'pike-push-up',       name: 'Pike Push-Up',          muscle: 'Shoulders' },

  // ---------- Biceps ----------
  { id: 'barbell-curl',       name: 'Barbell Curl',          muscle: 'Biceps' },
  { id: 'db-curl',            name: 'Dumbbell Curl',         muscle: 'Biceps' },
  { id: 'hammer-curl',        name: 'Hammer Curl',           muscle: 'Biceps' },
  { id: 'preacher-curl',      name: 'Preacher Curl',         muscle: 'Biceps' },
  { id: 'ez-bar-curl',        name: 'EZ-Bar Curl',           muscle: 'Biceps' },
  { id: 'incline-db-curl',    name: 'Incline Dumbbell Curl', muscle: 'Biceps' },
  { id: 'concentration-curl', name: 'Concentration Curl',    muscle: 'Biceps' },
  { id: 'cable-curl',         name: 'Cable Curl',            muscle: 'Biceps' },
  { id: 'rope-hammer-curl',   name: 'Rope Hammer Curl',      muscle: 'Biceps' },
  { id: 'spider-curl',        name: 'Spider Curl',           muscle: 'Biceps' },
  { id: 'machine-curl',       name: 'Curl (Machine)',        muscle: 'Biceps' },
  { id: 'zottman-curl',       name: 'Zottman Curl',          muscle: 'Biceps' },
  { id: 'drag-curl',          name: 'Drag Curl',             muscle: 'Biceps' },
  { id: 'reverse-curl',       name: 'Reverse Curl',          muscle: 'Biceps' },

  // ---------- Triceps ----------
  { id: 'tricep-pushdown',    name: 'Tricep Pushdown',       muscle: 'Triceps' },
  { id: 'skullcrusher',       name: 'Skullcrusher',          muscle: 'Triceps' },
  { id: 'overhead-tricep',    name: 'Overhead Tricep Ext.',  muscle: 'Triceps' },
  { id: 'rope-pushdown',      name: 'Rope Pushdown',         muscle: 'Triceps' },
  { id: 'tricep-dip',         name: 'Tricep Dip',            muscle: 'Triceps' },
  { id: 'bench-dip',          name: 'Bench Dip',             muscle: 'Triceps' },
  { id: 'db-overhead-ext',    name: 'Dumbbell Overhead Ext.', muscle: 'Triceps' },
  { id: 'cable-overhead-ext', name: 'Cable Overhead Ext.',   muscle: 'Triceps' },
  { id: 'kickback',           name: 'Tricep Kickback',       muscle: 'Triceps' },
  { id: 'jm-press',           name: 'JM Press',              muscle: 'Triceps' },
  { id: 'diamond-push-up',    name: 'Diamond Push-Up',       muscle: 'Triceps' },
  { id: 'machine-tricep-ext', name: 'Tricep Ext. (Machine)', muscle: 'Triceps' },

  // ---------- Forearms ----------
  { id: 'wrist-curl',         name: 'Wrist Curl',            muscle: 'Forearms' },
  { id: 'reverse-wrist-curl', name: 'Reverse Wrist Curl',    muscle: 'Forearms' },
  { id: 'farmers-walk',       name: "Farmer's Walk",         muscle: 'Forearms' },
  { id: 'dead-hang',          name: 'Dead Hang',             muscle: 'Forearms' },
  { id: 'plate-pinch',        name: 'Plate Pinch Hold',      muscle: 'Forearms' },
  { id: 'behind-back-wrist-curl', name: 'Behind-Back Wrist Curl', muscle: 'Forearms' },

  // ---------- Quads ----------
  { id: 'squat',              name: 'Back Squat',            muscle: 'Quads' },
  { id: 'front-squat',        name: 'Front Squat',           muscle: 'Quads' },
  { id: 'leg-press',          name: 'Leg Press',             muscle: 'Quads' },
  { id: 'leg-extension',      name: 'Leg Extension',         muscle: 'Quads' },
  { id: 'lunge',              name: 'Walking Lunge',         muscle: 'Quads' },
  { id: 'bulgarian-split',    name: 'Bulgarian Split Squat', muscle: 'Quads' },
  { id: 'hack-squat',         name: 'Hack Squat',            muscle: 'Quads' },
  { id: 'goblet-squat',       name: 'Goblet Squat',          muscle: 'Quads' },
  { id: 'smith-squat',        name: 'Smith Machine Squat',   muscle: 'Quads' },
  { id: 'pause-squat',        name: 'Pause Squat',           muscle: 'Quads' },
  { id: 'box-squat',          name: 'Box Squat',             muscle: 'Quads' },
  { id: 'split-squat',        name: 'Split Squat',           muscle: 'Quads' },
  { id: 'reverse-lunge',      name: 'Reverse Lunge',         muscle: 'Quads' },
  { id: 'step-up',            name: 'Step-Up',               muscle: 'Quads' },
  { id: 'sissy-squat',        name: 'Sissy Squat',           muscle: 'Quads' },
  { id: 'belt-squat',         name: 'Belt Squat',            muscle: 'Quads' },
  { id: 'pendulum-squat',     name: 'Pendulum Squat',        muscle: 'Quads' },
  { id: 'wall-sit',           name: 'Wall Sit',              muscle: 'Quads' },

  // ---------- Hamstrings ----------
  { id: 'romanian-deadlift',  name: 'Romanian Deadlift',     muscle: 'Hamstrings' },
  { id: 'leg-curl',           name: 'Leg Curl',              muscle: 'Hamstrings' },
  { id: 'seated-leg-curl',    name: 'Seated Leg Curl',       muscle: 'Hamstrings' },
  { id: 'stiff-leg-deadlift', name: 'Stiff-Leg Deadlift',    muscle: 'Hamstrings' },
  { id: 'db-rdl',             name: 'Dumbbell RDL',          muscle: 'Hamstrings' },
  { id: 'single-leg-rdl',     name: 'Single-Leg RDL',        muscle: 'Hamstrings' },
  { id: 'nordic-curl',        name: 'Nordic Curl',           muscle: 'Hamstrings' },
  { id: 'glute-ham-raise',    name: 'Glute-Ham Raise',       muscle: 'Hamstrings' },
  { id: 'cable-pull-through', name: 'Cable Pull-Through',    muscle: 'Hamstrings' },

  // ---------- Glutes ----------
  { id: 'hip-thrust',         name: 'Hip Thrust',            muscle: 'Glutes' },
  { id: 'glute-bridge',       name: 'Glute Bridge',          muscle: 'Glutes' },
  { id: 'single-leg-hip-thrust', name: 'Single-Leg Hip Thrust', muscle: 'Glutes' },
  { id: 'cable-kickback',     name: 'Cable Glute Kickback',  muscle: 'Glutes' },
  { id: 'hip-abduction',      name: 'Hip Abduction',         muscle: 'Glutes' },
  { id: 'sumo-squat',         name: 'Sumo Squat',            muscle: 'Glutes' },
  { id: 'curtsy-lunge',       name: 'Curtsy Lunge',          muscle: 'Glutes' },
  { id: 'frog-pump',          name: 'Frog Pump',             muscle: 'Glutes' },

  // ---------- Calves ----------
  { id: 'calf-raise',         name: 'Standing Calf Raise',   muscle: 'Calves' },
  { id: 'seated-calf-raise',  name: 'Seated Calf Raise',     muscle: 'Calves' },
  { id: 'leg-press-calf',     name: 'Leg Press Calf Raise',  muscle: 'Calves' },
  { id: 'single-leg-calf',    name: 'Single-Leg Calf Raise', muscle: 'Calves' },
  { id: 'donkey-calf-raise',  name: 'Donkey Calf Raise',     muscle: 'Calves' },
  { id: 'tibialis-raise',     name: 'Tibialis Raise',        muscle: 'Calves' },

  // ---------- Core ----------
  { id: 'plank',              name: 'Plank',                 muscle: 'Core' },
  { id: 'hanging-leg-raise',  name: 'Hanging Leg Raise',     muscle: 'Core' },
  { id: 'cable-crunch',       name: 'Cable Crunch',          muscle: 'Core' },
  { id: 'ab-wheel',           name: 'Ab Wheel Rollout',      muscle: 'Core' },
  { id: 'russian-twist',      name: 'Russian Twist',         muscle: 'Core' },
  { id: 'side-plank',         name: 'Side Plank',            muscle: 'Core' },
  { id: 'crunch',             name: 'Crunch',                muscle: 'Core' },
  { id: 'sit-up',             name: 'Sit-Up',                muscle: 'Core' },
  { id: 'decline-sit-up',     name: 'Decline Sit-Up',        muscle: 'Core' },
  { id: 'leg-raise',          name: 'Lying Leg Raise',       muscle: 'Core' },
  { id: 'captains-chair',     name: "Captain's Chair Raise", muscle: 'Core' },
  { id: 'mountain-climber',   name: 'Mountain Climber',      muscle: 'Core' },
  { id: 'dead-bug',           name: 'Dead Bug',              muscle: 'Core' },
  { id: 'bird-dog',           name: 'Bird Dog',              muscle: 'Core' },
  { id: 'pallof-press',       name: 'Pallof Press',          muscle: 'Core' },
  { id: 'woodchopper',        name: 'Cable Woodchopper',     muscle: 'Core' },
  { id: 'toes-to-bar',        name: 'Toes-to-Bar',           muscle: 'Core' },
  { id: 'hollow-hold',        name: 'Hollow Body Hold',      muscle: 'Core' },
  { id: 'v-up',               name: 'V-Up',                  muscle: 'Core' },
  { id: 'machine-crunch',     name: 'Crunch (Machine)',      muscle: 'Core' },

  // ---------- Olympic & power ----------
  { id: 'power-clean',        name: 'Power Clean',           muscle: 'Olympic' },
  { id: 'hang-clean',         name: 'Hang Clean',            muscle: 'Olympic' },
  { id: 'clean-and-jerk',     name: 'Clean & Jerk',          muscle: 'Olympic' },
  { id: 'snatch',             name: 'Snatch',                muscle: 'Olympic' },
  { id: 'power-snatch',       name: 'Power Snatch',          muscle: 'Olympic' },
  { id: 'high-pull',          name: 'High Pull',             muscle: 'Olympic' },
  { id: 'thruster',           name: 'Thruster',              muscle: 'Olympic' },
  { id: 'box-jump',           name: 'Box Jump',              muscle: 'Olympic' },
  { id: 'kb-swing',           name: 'Kettlebell Swing',      muscle: 'Olympic' },
  { id: 'med-ball-slam',      name: 'Medicine Ball Slam',    muscle: 'Olympic' },

  // ---------- Cardio ----------
  { id: 'treadmill-run',      name: 'Treadmill Run',         muscle: 'Cardio' },
  { id: 'outdoor-run',        name: 'Outdoor Run',           muscle: 'Cardio' },
  { id: 'rowing-machine',     name: 'Rowing Machine',        muscle: 'Cardio' },
  { id: 'stationary-bike',    name: 'Stationary Bike',       muscle: 'Cardio' },
  { id: 'elliptical',         name: 'Elliptical',            muscle: 'Cardio' },
  { id: 'stair-climber',      name: 'Stair Climber',         muscle: 'Cardio' },
  { id: 'ski-erg',            name: 'Ski Erg',               muscle: 'Cardio' },
  { id: 'assault-bike',       name: 'Assault Bike',          muscle: 'Cardio' },
  { id: 'jump-rope',          name: 'Jump Rope',             muscle: 'Cardio' },
  { id: 'sled-push',          name: 'Sled Push',             muscle: 'Cardio' },
  { id: 'sled-drag',          name: 'Sled Drag',             muscle: 'Cardio' },
  { id: 'incline-walk',       name: 'Incline Walk',          muscle: 'Cardio' },
];

const MUSCLE_ORDER = [
  'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms',
  'Quads', 'Hamstrings', 'Glutes', 'Calves', 'Core',
  'Olympic', 'Cardio', 'Other',
];
